In [1]:
import pandas as pd

 https://www.washingtonpost.com/news/wonk/wp/2015/04/23/a-stunning-visualization-of-our-divided-congress/
 https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0123507

In [93]:
# Read in dataset
data = pd.read_csv('https://raw.githubusercontent.com/campkels/Intro-SNA-Demo/master/VotingData/115Congress_VotesData.csv')
print(data.shape)
data.head(5)

(27398, 8)

,Unnamed: 0,person,state,district,vote,name,party,session
0,0,300002,TN,NaN,Not Voting,Sen. Lamar Alexander [R],Republican,1
1,1,300018,WA,NaN,Yea,"Sen. Maria Cantwell [D, 2001-2024]",Democrat,1
2,2,300019,DE,NaN,Yea,"Sen. Thomas Carper [D, 2001-2024]",Democrat,1
3,3,300023,MS,NaN,Yea,"Sen. Thad Cochran [R, 1979-2018]",Republican,1
4,4,300025,ME,NaN,Yea,Sen. Susan Collins [R],Republican,1

In [94]:
# Limit to voters
votesdata = data.loc[((data['vote'] == 'Yea') | (data['vote'] == 'Nay')), ] # no "Not Voting" or "Present"
print(votesdata.shape)
votesdata.head(5)

(26510, 8)

,Unnamed: 0,person,state,district,vote,name,party,session
1,1,300018,WA,NaN,Yea,"Sen. Maria Cantwell [D, 2001-2024]",Democrat,1
2,2,300019,DE,NaN,Yea,"Sen. Thomas Carper [D, 2001-2024]",Democrat,1
3,3,300023,MS,NaN,Yea,"Sen. Thad Cochran [R, 1979-2018]",Republican,1
4,4,300025,ME,NaN,Yea,Sen. Susan Collins [R],Republican,1
5,5,300027,TX,NaN,Yea,Sen. John Cornyn [R],Republican,1

### Create Nodes Table (feat. Data Cleaning)

Good guide for groupby https://www.shanelynn.ie/summarising-aggregation-and-grouping-data-in-python-pandas/

In [95]:
# Try and get nodes table (discover some dirty data)
votesdata.groupby(['person', 'state', 'name', 'party']).agg({'person': "count"})

                                                                  person
person state name                                    party
300002 TN    Sen. Lamar Alexander [R]                Republican      260
300018 WA    Sen. Maria Cantwell [D, 2001-2024]      Democrat        274
300019 DE    Sen. Thomas Carper [D, 2001-2024]       Democrat        273
300023 MS    Sen. Thad Cochran [R, 1979-2018]        Republican       62
300025 ME    Sen. Susan Collins [R]                  Republican      274
300027 TX    Sen. John Cornyn [R]                    Republican      272
300030 ID    Sen. Michael Crapo [R]                  Republican      270
300038 IL    Sen. Richard Durbin [D]                 Democrat        267
300041 WY    Sen. Michael Enzi [R]                   Republican      274
300043 CA    Sen. Dianne Feinstein [D, 1992-2024]    Democrat        262
300047 SC    Sen. Lindsey Graham [R]                 Republican      252
300048 IA    Sen. Charles “Chuck” Grassley [R]       Republican      274
300052 UT    Sen. Orrin Hatch [R, 1977-2018]         Republican      272
300055 OK    Sen. James “Jim” Inhofe [R]             Republican      263
300062 AZ    Sen. Jon Kyl [R, 2018-2018]             Republican       71
300065 VT    Sen. Patrick Leahy [D]                  Democrat        262
300072 KY    Sen. Mitch McConnell [R]                Republican      274
300075 AK    Sen. Lisa Murkowski [R]                 Republican      263
300076 WA    Sen. Patty Murray [D]                   Democrat        261
300078 FL    Sen. Bill Nelson [D, 2001-2018]         Democrat        244
300081 RI    Sen. John “Jack” Reed [D]               Democrat        274
300083 KS    Sen. Pat Roberts [R]                    Republican      271
300087 NY    Sen. Charles “Chuck” Schumer [D]        Democrat        273
300089 AL    Sen. Richard Shelby [R]                 Republican      272
300093 MI    Sen. Debbie Stabenow [D, 2001-2018]     Democrat        273
300100 OR    Sen. Ron Wyden [D]                      Democrat        273
400013 WI    Sen. Tammy Baldwin [D, 2013-2024]       Democrat        273
400034 MO    Sen. Roy Blunt [R]                      Republican      268
400040 AR    Sen. John Boozman [R]                   Republican      270
400050 OH    Sen. Sherrod Brown [D, 2007-2024]       Democrat        272
...                                                                  ...
412492 KY    Sen. Rand Paul [R]                      Republican      266
412494 ND    Sen. John Hoeven [R]                    Republican      271
412495 UT    Sen. Mike Lee [R]                       Republican      266
412496 WI    Sen. Ron Johnson [R]                    Republican      270
412507 HI    Sen. Brian Schatz [D]                   Democrat        266
412508 AR    Sen. Tom Cotton [R]                     Republican      272
412533 IL    Sen. Tammy Duckworth [D]                Democrat        201
412542 MA    Sen. Elizabeth Warren [D, 2013-2024]    Democrat        274
412545 ME    Sen. Angus King [I, 2013-2024]          Independent     274
412549 MT    Sen. Steve Daines [R]                   Republican      272
412554 ND    Sen. Heidi Heitkamp [D, 2013-2018]      Democrat        258
412556 NE    Sen. Deb Fischer [R, 2013-2024]         Republican      270
412573 TX    Sen. Ted Cruz [R, 2013-2024]            Republican      249
412582 VA    Sen. Timothy “Tim” Kaine [D, 2013-2024] Democrat        274
412598 NJ    Sen. Cory Booker [D]                    Democrat        259
412665 AK    Sen. Dan Sullivan [R]                   Republican      265
412666 GA    Sen. David Perdue [R]                   Republican      268
412667 IA    Sen. Joni Ernst [R]                     Republican      274
412668 NC    Sen. Thom Tillis [R]                    Republican      252
412669 SD    Sen. Mike Rounds [R]                    Republican      265
412671 NE    Sen. Benjamin Sasse [R]                 Republican      272
412678 CA    Sen. Kamala Harris [D]                  Democrat        273
412679 LA    Sen. John Kennedy [R]                   Republican      272
412680 NH    Sen. Margaret “Maggie” Hassan [D]       Democrat        271
412681 NV    Sen. Catherine Cortez Masto [D]         Democrat        272
412741 AL    Sen. Doug Jones [D]                     Democrat        269
412742 MN    Sen. Tina Smith [D, 2018-2020]          Democrat        239
             Sen. Tina Smith [D]                     Democrat         35
412743 MS    Sen. Cindy Hyde-Smith [R, 2018-2020]    Republican      178
             Sen. Cindy Hyde-Smith [R]               Republican       27

[103 rows x 1 columns]

In [96]:
# Not actually caused by missing ID
votesdata.loc[votesdata.person.isnull(),]

Empty DataFrame
Columns: [Unnamed: 0, person, state, district, vote, name, party, session]
Index: []

In [97]:
# Fix mult names / ID issue (Causing missing ID issue)

# Group by person and name
sumidname = votesdata.groupby(['person', 'name'], as_index=False).agg({'party': "count"})
# Group by name to get the # of names associated with an ID
sumid = sumidname.groupby(['person'], as_index=False).agg({'party': "count"})
# Rename the summary variable for clarity
sumid = sumid.rename(index=str, columns={"party": "cntnames"})
# List ID's with muliple names associated with them (needs cleaning)
sumid.loc[sumid['cntnames'] > 1, ]

     person  cntnames
100  412742         2
101  412743         2

In [98]:
# Look at associated names
sumidname.loc[((sumidname['person'] == 412742) | (sumidname['person'] == 412743)),]

     person                                  name  party
100  412742        Sen. Tina Smith [D, 2018-2020]    239
101  412742                   Sen. Tina Smith [D]     35
102  412743  Sen. Cindy Hyde-Smith [R, 2018-2020]    178
103  412743             Sen. Cindy Hyde-Smith [R]     27

In [99]:
# Replace values
votesdata_clean = votesdata.replace({'name': {'Sen. Tina Smith [D]': 'Sen. Tina Smith [D, 2018-2020]', \
                                              'Sen. Cindy Hyde-Smith [R]': 'Sen. Cindy Hyde-Smith [R, 2018-2020]'}})
# Check with Group by person and name, before and after
print(votesdata.groupby(['person', 'name'], as_index=False).agg({'party': "count"}).shape)
print(votesdata_clean.groupby(['person', 'name'], as_index=False).agg({'party': "count"}).shape)

(104, 3)
(102, 3)

In [100]:
# Get nodes table (take 2)
#votesdata_clean.groupby(['person', 'state', 'name', 'party']).agg({'person': "count"})
votesdata_clean.groupby(['person', 'state', 'name', 'party'], as_index=False).agg({'vote': "count"}).shape

(101, 5)

In [102]:
votesdata_clean[votesdata_clean['party'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, person, state, district, vote, name, party, session]
Index: []

In [103]:
votesdata_clean[votesdata_clean['state'].isnull()]

,Unnamed: 0,person,state,district,vote,name,party,session
2138,2138,400315,NaN,NaN,Yea,Vice President Mike Pence [R],Vice President,22
2239,2239,400315,NaN,NaN,Yea,Vice President Mike Pence [R],Vice President,23
3940,3940,400315,NaN,NaN,Yea,Vice President Mike Pence [R],Vice President,40
24831,24831,400315,NaN,NaN,Yea,Vice President Mike Pence [R],Vice President,249
25032,25032,400315,NaN,NaN,Yea,Vice President Mike Pence [R],Vice President,251
25733,25733,400315,NaN,NaN,Yea,Vice President Mike Pence [R],Vice President,258
27334,27334,400315,NaN,NaN,Yea,Vice President Mike Pence [R],Vice President,274

In [104]:
# Replace state column missings
votesdata_clean['state'].fillna('None', inplace=True)
# Check
votesdata_clean[votesdata_clean['state'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, person, state, district, vote, name, party, session]
Index: []

In [105]:
# Get nodes table (take 2)
votesdata_clean.groupby(['person', 'state', 'name', 'party'], as_index=False).agg({'vote': "count"}).shape

(102, 5)

In [106]:
nodetbl = votesdata_clean.groupby(['person', 'state', 'name', 'party'], as_index=False).agg({'vote': "count"})
# Drop summary var - Doesnt represent # votes because can be "Present" or "Not Voting"
nodetbl = nodetbl.drop(['vote'], axis=1)

nodetbl

     person state                                     name        party
0    300002    TN                 Sen. Lamar Alexander [R]   Republican
1    300018    WA       Sen. Maria Cantwell [D, 2001-2024]     Democrat
2    300019    DE        Sen. Thomas Carper [D, 2001-2024]     Democrat
3    300023    MS         Sen. Thad Cochran [R, 1979-2018]   Republican
4    300025    ME                   Sen. Susan Collins [R]   Republican
5    300027    TX                     Sen. John Cornyn [R]   Republican
6    300030    ID                   Sen. Michael Crapo [R]   Republican
7    300038    IL                  Sen. Richard Durbin [D]     Democrat
8    300041    WY                    Sen. Michael Enzi [R]   Republican
9    300043    CA     Sen. Dianne Feinstein [D, 1992-2024]     Democrat
10   300047    SC                  Sen. Lindsey Graham [R]   Republican
11   300048    IA        Sen. Charles “Chuck” Grassley [R]   Republican
12   300052    UT          Sen. Orrin Hatch [R, 1977-2018]   Republican
13   300055    OK              Sen. James “Jim” Inhofe [R]   Republican
14   300062    AZ              Sen. Jon Kyl [R, 2018-2018]   Republican
15   300065    VT                   Sen. Patrick Leahy [D]     Democrat
16   300072    KY                 Sen. Mitch McConnell [R]   Republican
17   300075    AK                  Sen. Lisa Murkowski [R]   Republican
18   300076    WA                    Sen. Patty Murray [D]     Democrat
19   300078    FL          Sen. Bill Nelson [D, 2001-2018]     Democrat
20   300081    RI                Sen. John “Jack” Reed [D]     Democrat
21   300083    KS                     Sen. Pat Roberts [R]   Republican
22   300087    NY         Sen. Charles “Chuck” Schumer [D]     Democrat
23   300089    AL                  Sen. Richard Shelby [R]   Republican
24   300093    MI      Sen. Debbie Stabenow [D, 2001-2018]     Democrat
25   300100    OR                       Sen. Ron Wyden [D]     Democrat
26   400013    WI        Sen. Tammy Baldwin [D, 2013-2024]     Democrat
27   400034    MO                       Sen. Roy Blunt [R]   Republican
28   400040    AR                    Sen. John Boozman [R]   Republican
29   400050    OH        Sen. Sherrod Brown [D, 2007-2024]     Democrat
..      ...   ...                                      ...          ...
72   412490    CT              Sen. Richard Blumenthal [D]     Democrat
73   412491    FL                     Sen. Marco Rubio [R]   Republican
74   412492    KY                       Sen. Rand Paul [R]   Republican
75   412494    ND                     Sen. John Hoeven [R]   Republican
76   412495    UT                        Sen. Mike Lee [R]   Republican
77   412496    WI                     Sen. Ron Johnson [R]   Republican
78   412507    HI                    Sen. Brian Schatz [D]     Democrat
79   412508    AR                      Sen. Tom Cotton [R]   Republican
80   412533    IL                 Sen. Tammy Duckworth [D]     Democrat
81   412542    MA     Sen. Elizabeth Warren [D, 2013-2024]     Democrat
82   412545    ME           Sen. Angus King [I, 2013-2024]  Independent
83   412549    MT                    Sen. Steve Daines [R]   Republican
84   412554    ND       Sen. Heidi Heitkamp [D, 2013-2018]     Democrat
85   412556    NE          Sen. Deb Fischer [R, 2013-2024]   Republican
86   412573    TX             Sen. Ted Cruz [R, 2013-2024]   Republican
87   412582    VA  Sen. Timothy “Tim” Kaine [D, 2013-2024]     Democrat
88   412598    NJ                     Sen. Cory Booker [D]     Democrat
89   412665    AK                    Sen. Dan Sullivan [R]   Republican
90   412666    GA                    Sen. David Perdue [R]   Republican
91   412667    IA                      Sen. Joni Ernst [R]   Republican
92   412668    NC                     Sen. Thom Tillis [R]   Republican
93   412669    SD                     Sen. Mike Rounds [R]   Republican
94   412671    NE                  Sen. Benjamin Sasse [R]   Republican
95   412678    CA                   Sen. Kamala Harris [D]     Democrat
96   412679    LA                    Sen. John Kennedy [R]   Republican
97   412680    NH        Sen. Margaret “Maggie” Hassan [D]     Democrat
98   412681    NV          Sen. Catherine Cortez Masto [D]     Democrat
99   412741    AL                      Sen. Doug Jones [D]     Democrat
100  412742    MN           Sen. Tina Smith [D, 2018-2020]     Democrat
101  412743    MS     Sen. Cindy Hyde-Smith [R, 2018-2020]   Republican

[102 rows x 4 columns]

### Create Edges Table

In [107]:
votesdata_clean

,Unnamed: 0,person,state,district,vote,name,party,session
1,1,300018,WA,NaN,Yea,"Sen. Maria Cantwell [D, 2001-2024]",Democrat,1
2,2,300019,DE,NaN,Yea,"Sen. Thomas Carper [D, 2001-2024]",Democrat,1
3,3,300023,MS,NaN,Yea,"Sen. Thad Cochran [R, 1979-2018]",Republican,1
4,4,300025,ME,NaN,Yea,Sen. Susan Collins [R],Republican,1
5,5,300027,TX,NaN,Yea,Sen. John Cornyn [R],Republican,1
6,6,300030,ID,NaN,Yea,Sen. Michael Crapo [R],Republican,1
7,7,300038,IL,NaN,Yea,Sen. Richard Durbin [D],Democrat,1
8,8,300041,WY,NaN,Yea,Sen. Michael Enzi [R],Republican,1
9,9,300043,CA,NaN,Yea,"Sen. Dianne Feinstein [D, 1992-2024]",Democrat,1
10,10,300047,SC,NaN,Yea,Sen. Lindsey Graham [R],Republican,1
11,11,300048,IA,NaN,Yea,Sen. Charles “Chuck” Grassley [R],Republican,1
13,13,300055,OK,NaN,Yea,Sen. James “Jim” Inhofe [R],Republican,1
14,14,300065,VT,NaN,Yea,Sen. Patrick Leahy [D],Democrat,1
16,16,300072,KY,NaN,Yea,Sen. Mitch McConnell [R],Republican,1
18,18,300076,WA,NaN,Yea,Sen. Patty Murray [D],Democrat,1
19,19,300078,FL,NaN,Yea,"Sen. Bill Nelson [D, 2001-2018]",Democrat,1
20,20,300081,RI,NaN,Yea,Sen. John “Jack” Reed [D],Democrat,1
21,21,300083,KS,NaN,Yea,Sen. Pat Roberts [R],Republican,1
22,22,300087,NY,NaN,Yea,Sen. Charles “Chuck” Schumer [D],Democrat,1
23,23,300089,AL,NaN,Yea,Sen. Richard Shelby [R],Republican,1
24,24,300093,MI,NaN,Yea,"Sen. Debbie Stabenow [D, 2001-2018]",Democrat,1
25,25,300100,OR,NaN,Nay,Sen. Ron Wyden [D],Democrat,1
26,26,400013,WI,NaN,Yea,"Sen. Tammy Baldwin [D, 2013-2024]",Democrat,1
27,27,400034,MO,NaN,Yea,Sen. Roy Blunt [R],Republican,1
28,28,400040,AR,NaN,Yea,Sen. John Boozman [R],Republican,1
29,29,400050,OH,NaN,Yea,"Sen. Sherrod Brown [D, 2007-2024]",Democrat,1
31,31,400061,WV,NaN,Yea,Sen. Shelley Capito [R],Republican,1
32,32,400064,MD,NaN,Yea,"Sen. Benjamin Cardin [D, 2007-2024]",Democrat,1
33,33,400134,AZ,NaN,Yea,"Sen. Jeff Flake [R, 2013-2018]",Republican,1
34,34,400194,GA,NaN,Yea,Sen. John “Johnny” Isakson [R],Republican,1
...,...,...,...,...,...,...,...,...
27367,27367,412471,SC,NaN,Yea,Sen. Tim Scott [R],Republican,274
27368,27368,412490,CT,NaN,Nay,Sen. Richard Blumenthal [D],Democrat,274
27369,27369,412491,FL,NaN,Yea,Sen. Marco Rubio [R],Republican,274
27371,27371,412494,ND,NaN,Yea,Sen. John Hoeven [R],Republican,274
27372,27372,412495,UT,NaN,Yea,Sen. Mike Lee [R],Republican,274
27373,27373,412496,WI,NaN,Yea,Sen. Ron Johnson [R],Republican,274
27374,27374,412507,HI,NaN,Nay,Sen. Brian Schatz [D],Democrat,274
27375,27375,412508,AR,NaN,Yea,Sen. Tom Cotton [R],Republican,274
27376,27376,412533,IL,NaN,Nay,Sen. Tammy Duckworth [D],Democrat,274
27377,27377,412542,MA,NaN,Nay,"Sen. Elizabeth Warren [D, 2013-2024]",Democrat,274
27378,27378,412545,ME,NaN,Nay,"Sen. Angus King [I, 2013-2024]",Independent,274
27379,27379,412549,MT,NaN,Yea,Sen. Steve Daines [R],Republican,274
27380,27380,412554,ND,NaN,Nay,"Sen. Heidi Heitkamp [D, 2013-2018]",Democrat,274
27381,27381,412556,NE,NaN,Yea,"Sen. Deb Fischer [R, 2013-2024]",Republican,274
27382,27382,412573,TX,NaN,Yea,"Sen. Ted Cruz [R, 2013-2024]",Republican,274
27383,27383,412582,VA,NaN,Nay,"Sen. Timothy “Tim” Kaine [D, 2013-2024]",Democrat,274
27384,27384,412598,NJ,NaN,Nay,Sen. Cory Booker [D],Democrat,274
27385,27385,412665,AK,NaN,Yea,Sen. Dan Sullivan [R],Republican,274
27386,27386,412666,GA,NaN,Yea,Sen. David Perdue [R],Republican,274
27387,27387,412667,IA,NaN,Yea,Sen. Joni Ernst [R],Republican,274
27388,27388,412668,NC,NaN,Yea,Sen. Thom Tillis [R],Republican,274
27389,27389,412669,SD,NaN,Yea,Sen. Mike Rounds [R],Republican,274
27390,27390,412671,NE,NaN,Yea,Sen. Benjamin Sasse [R],Republican,274
27391,27391,412678,CA,NaN,Nay,Sen. Kamala Harris [D],Democrat,274
27392,27392,412679,LA,NaN,Yea,Sen. John Kennedy [R],Republican,274
27393,27393,412680,NH,NaN,Nay,Sen. Margaret “Maggie” Hassan [D],Democrat,274
27394,27394,412681,NV,NaN,Nay,Sen. Catherine Cortez Masto [D],Democrat,274
27395,27395,412741,AL,NaN,Yea,Sen. Doug Jones [D],Democrat,274
27396,27396,412742,MN,NaN,Nay,"Sen. Tina Smith [D, 2018-2020]",Democrat,274
27397,27397,412743,MS,NaN,Yea,"Sen. Cindy Hyde-Smith [R, 2018-2020]",Republican,274

### (graphic with what we have and what we want)

In [139]:
# Test set (assuming same vote)
testset = pd.DataFrame({ 'session' : [1, 1, 1, 2, 2, 2],
                         'person' : ['bob', 'mary', 'marsha', 'bob', 'mary', 'myles']})

testset

   person  session
0     bob        1
1    mary        1
2  marsha        1
3     bob        2
4    mary        2
5   myles        2

https://www.shanelynn.ie/summarising-aggregation-and-grouping-data-in-python-pandas/ - 
The groupby() function returns a GroupBy object, but essentially describes how the rows of  the original data set has been split. the GroupBy object .groups variable is a dictionary whose keys are the computed unique groups and corresponding values being the axis labels belonging to each group.

In [150]:
# Need to chunk by session - because we only want to pair within a session - GROUPBY!
grouptestset = testset.groupby('session')
grouptestset.groups.keys()

dict_keys([1, 2])

In [165]:
print(grouptestset.groups[1]) #values for key are the indexes of all the records for the key

Int64Index([0, 1, 2], dtype='int64')

In [200]:
print(grouptestset.get_group(1))
print()
print(grouptestset.get_group(2))

   person  session
0     bob        1
1    mary        1
2  marsha        1

  person  session
3    bob        2
4   mary        2
5  myles        2

In [202]:
# Get all unique pairs within a session = COMBINATIONS
# want to sort so all later the pairs are in same order
sesh1people = grouptestset.get_group(1).sort_values(by=['person'])['person'].values
sesh1people

array(['bob', 'marsha', 'mary'], dtype=object)

In [203]:
from itertools import combinations

list(combinations(sesh1people, 2))

[('bob', 'marsha'), ('bob', 'mary'), ('marsha', 'mary')]

In [209]:
# but we need to do this for each session! APPLY!
# Apply can send an entire column to a function, or every row to a function

seshcombos = grouptestset['person'].apply(lambda x : list(combinations(x.values,2)))
seshcombos

session
1    [(bob, mary), (bob, marsha), (mary, marsha)]
2      [(bob, mary), (bob, myles), (mary, myles)]
Name: person, dtype: object

In [188]:
# Some other magic to shape into a dataset
seshcombos.apply(pd.Series).stack().reset_index(level=0, name='covote')

   session          covote
0        1     (bob, mary)
1        1   (bob, marsha)
2        1  (mary, marsha)
0        2     (bob, mary)
1        2    (bob, myles)
2        2   (mary, myles)

### Do it for reals!

In [211]:
# Create same vote sets (sorting so tuples are always in the same order)
yayvotes = votesdata_clean.loc[votesdata_clean['vote'] == 'Yea', ].sort_values(by=['person'])
nayvotes = votesdata_clean.loc[votesdata_clean['vote'] == 'Nay', ].sort_values(by=['person'])

# Transform to covote sets
yaytuples = yayvotes.groupby('session')['person'].apply(lambda x : list(combinations(x.values,2))).apply(pd.Series).stack().reset_index(level=0,name='covote')
naytuples = nayvotes.groupby('session')['person'].apply(lambda x : list(combinations(x.values,2))).apply(pd.Series).stack().reset_index(level=0,name='covote')

print(yaytuples.shape)
print(naytuples.shape)

(712642, 2)
(153463, 2)

In [195]:
# Why is our data so BIG now?!

# Example - session 1 Yays
print(yayvotes.loc[yayvotes['session'] == 1, ].shape) # 81 people voted yay in the first session
print(yaytuples.loc[yaytuples['session'] == 1, ].shape) # translates to 3240 unique combinations!

#https://stackoverflow.com/questions/18859430/how-do-i-get-the-total-number-of-unique-pairs-of-a-set-in-the-database
# test with =COMBIN(81,2) in excel

(81, 8)
(3240, 2)

In [217]:
# Combine Yay and Nay sets
alltuples = yaytuples.append(naytuples, ignore_index=True)
print(alltuples.shape)
alltuples.head()

(866105, 2)

   session            covote
0        1  (300018, 300019)
1        1  (300018, 300023)
2        1  (300018, 300025)
3        1  (300018, 300027)
4        1  (300018, 300030)

In [231]:
# check no covotes are out of order
# alltuples[['p1', 'p2']] = pd.DataFrame(alltuples['covote'].tolist(), index=alltuples.index)  
# alltuples['negcheck'] = alltuples['p1'] - alltuples['p2']
# alltuples.loc[alltuples['negcheck'] > 0, ]

Empty DataFrame
Columns: [session, covote, negcheck, p1, p2]
Index: []

In [276]:
# Summarize by each pair (get the total amount they agreed - dont care if it was yay or nay agreement)
groupedtups = alltuples.groupby(['covote'], as_index=False).agg({'session': "count"})
# Rename the summary variable for clarity
groupedtups = groupedtups.rename(index=str, columns={"session": "agreecnt"})
# Seperate tuple
groupedtups[['person1', 'person2']] = pd.DataFrame(groupedtups['covote'].tolist(), index=groupedtups.index) 

print(groupedtups.shape)
groupedtups.head()

(5101, 4)

             covote  agreecnt  person1  person2
0  (300002, 300018)       124   300002   300018
1  (300002, 300019)       155   300002   300019
2  (300002, 300023)        54   300002   300023
3  (300002, 300025)       243   300002   300025
4  (300002, 300027)       245   300002   300027

In [277]:
# Implement "threshold" from paper for edges?
edgetbl = groupedtups

https://networkx.github.io/documentation/stable/tutorial.html
https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

In [278]:
import networkx as nx
print(nx.__version__) # mine is 2.2

G = nx.from_pandas_edgelist(edgetbl, 'person1', 'person2', 'agreecnt')

2.2

In [279]:
G.number_of_nodes()

102

In [283]:
G.number_of_edges()

5101

In [280]:
# remember nodes table
nodetbl.head()

   person state                                name       party
0  300002    TN            Sen. Lamar Alexander [R]  Republican
1  300018    WA  Sen. Maria Cantwell [D, 2001-2024]    Democrat
2  300019    DE   Sen. Thomas Carper [D, 2001-2024]    Democrat
3  300023    MS    Sen. Thad Cochran [R, 1979-2018]  Republican
4  300025    ME              Sen. Susan Collins [R]  Republican

In [286]:
# Add attributes from nodes table to graph
nx.set_node_attributes(G, pd.Series(nodetbl.state.values, index=nodetbl.person).to_dict(), 'state')
nx.set_node_attributes(G, pd.Series(nodetbl.name.values, index=nodetbl.person).to_dict(), 'name')
nx.set_node_attributes(G, pd.Series(nodetbl.party.values, index=nodetbl.person).to_dict(), 'party')

In [287]:
# check
G.nodes.data()

NodeDataView({300002: {'state': 'TN', 'name': 'Sen. Lamar Alexander [R]', 'party': 'Republican'}, 300018: {'state': 'WA', 'name': 'Sen. Maria Cantwell [D, 2001-2024]', 'party': 'Democrat'}, 300019: {'state': 'DE', 'name': 'Sen. Thomas Carper [D, 2001-2024]', 'party': 'Democrat'}, 300023: {'state': 'MS', 'name': 'Sen. Thad Cochran [R, 1979-2018]', 'party': 'Republican'}, 300025: {'state': 'ME', 'name': 'Sen. Susan Collins [R]', 'party': 'Republican'}, 300027: {'state': 'TX', 'name': 'Sen. John Cornyn [R]', 'party': 'Republican'}, 300030: {'state': 'ID', 'name': 'Sen. Michael Crapo [R]', 'party': 'Republican'}, 300038: {'state': 'IL', 'name': 'Sen. Richard Durbin [D]', 'party': 'Democrat'}, 300041: {'state': 'WY', 'name': 'Sen. Michael Enzi [R]', 'party': 'Republican'}, 300043: {'state': 'CA', 'name': 'Sen. Dianne Feinstein [D, 1992-2024]', 'party': 'Democrat'}, 300047: {'state': 'SC', 'name': 'Sen. Lindsey Graham [R]', 'party': 'Republican'}, 300048: {'state': 'IA', 'name': 'Sen. Charles “Chuck” Grassley [R]', 'party': 'Republican'}, 300052: {'state': 'UT', 'name': 'Sen. Orrin Hatch [R, 1977-2018]', 'party': 'Republican'}, 300055: {'state': 'OK', 'name': 'Sen. James “Jim” Inhofe [R]', 'party': 'Republican'}, 300062: {'state': 'AZ', 'name': 'Sen. Jon Kyl [R, 2018-2018]', 'party': 'Republican'}, 300065: {'state': 'VT', 'name': 'Sen. Patrick Leahy [D]', 'party': 'Democrat'}, 300072: {'state': 'KY', 'name': 'Sen. Mitch McConnell [R]', 'party': 'Republican'}, 300075: {'state': 'AK', 'name': 'Sen. Lisa Murkowski [R]', 'party': 'Republican'}, 300076: {'state': 'WA', 'name': 'Sen. Patty Murray [D]', 'party': 'Democrat'}, 300078: {'state': 'FL', 'name': 'Sen. Bill Nelson [D, 2001-2018]', 'party': 'Democrat'}, 300081: {'state': 'RI', 'name': 'Sen. John “Jack” Reed [D]', 'party': 'Democrat'}, 300083: {'state': 'KS', 'name': 'Sen. Pat Roberts [R]', 'party': 'Republican'}, 300087: {'state': 'NY', 'name': 'Sen. Charles “Chuck” Schumer [D]', 'party': 'Democrat'}, 300089: {'state': 'AL', 'name': 'Sen. Richard Shelby [R]', 'party': 'Republican'}, 300093: {'state': 'MI', 'name': 'Sen. Debbie Stabenow [D, 2001-2018]', 'party': 'Democrat'}, 300100: {'state': 'OR', 'name': 'Sen. Ron Wyden [D]', 'party': 'Democrat'}, 400013: {'state': 'WI', 'name': 'Sen. Tammy Baldwin [D, 2013-2024]', 'party': 'Democrat'}, 400034: {'state': 'MO', 'name': 'Sen. Roy Blunt [R]', 'party': 'Republican'}, 400040: {'state': 'AR', 'name': 'Sen. John Boozman [R]', 'party': 'Republican'}, 400050: {'state': 'OH', 'name': 'Sen. Sherrod Brown [D, 2007-2024]', 'party': 'Democrat'}, 400054: {'state': 'NC', 'name': 'Sen. Richard Burr [R]', 'party': 'Republican'}, 400061: {'state': 'WV', 'name': 'Sen. Shelley Capito [R]', 'party': 'Republican'}, 400064: {'state': 'MD', 'name': 'Sen. Benjamin Cardin [D, 2007-2024]', 'party': 'Democrat'}, 400134: {'state': 'AZ', 'name': 'Sen. Jeff Flake [R, 2013-2018]', 'party': 'Republican'}, 400194: {'state': 'GA', 'name': 'Sen. John “Johnny” Isakson [R]', 'party': 'Republican'}, 400253: {'state': 'MA', 'name': 'Sen. Edward “Ed” Markey [D]', 'party': 'Democrat'}, 400272: {'state': 'NJ', 'name': 'Sen. Robert “Bob” Menendez [D, 2006-2024]', 'party': 'Democrat'}, 400284: {'state': 'KS', 'name': 'Sen. Jerry Moran [R]', 'party': 'Republican'}, 400315: {'state': 'None', 'name': 'Vice President Mike Pence [R]', 'party': 'Vice President'}, 400325: {'state': 'OH', 'name': 'Sen. Robert “Rob” Portman [R]', 'party': 'Republican'}, 400357: {'state': 'VT', 'name': 'Sen. Bernard “Bernie” Sanders [I, 2007-2024]', 'party': 'Independent'}, 400408: {'state': 'PA', 'name': 'Sen. Patrick “Pat” Toomey [R]', 'party': 'Republican'}, 400413: {'state': 'NM', 'name': 'Sen. Tom Udall [D]', 'party': 'Democrat'}, 400415: {'state': 'MD', 'name': 'Sen. Chris Van Hollen Jr. [D]', 'party': 'Democrat'}, 400432: {'state': 'MS', 'name': 'Sen. Roger Wicker [R, 2007-2024]', 'party': 'Republican'}, 400546: {'state': 'SD', 'name': 'Sen. John Thune [R]', 'party': 'Republican'}, 412194: {'state': 'CT', 'name': 'Sen. Christopher Murphy [D, 2013-2024]', 'party': 'Democrat'}, 412200: {'state': 'HI', 'name': 'Sen. Mazie Hirono [D, 2013-2024]', 'party': 'Democrat'}, 412205: {'state': 'IN', 'name': 'Sen. Joe Donnelly [D, 2013-2018]', 'party': 'Democrat'}, 412218: {'state': 'NV', 'name': 'Sen. Dean Heller [R, 2011-2018]', 'party': 'Republican'}, 412223: {'state': 'NY', 'name': 'Sen. Kirsten Gillibrand [D, 2009-2024]', 'party': 'Democrat'}, 412242: {'state': 'MN', 'name': 'Sen. Amy Klobuchar [D, 2007-2018]', 'party': 'Democrat'}, 412243: {'state': 'MO', 'name': 'Sen. Claire McCaskill [D, 2007-2018]', 'party': 'Democrat'}, 412244: {'state': 'MT', 'name': 'Sen. Jon Tester [D, 2007-2024]', 'party': 'Democrat'}, 412246: {'state': 'PA', 'name': 'Sen. Robert “Bob” Casey Jr. [D, 2007-2024]', 'party': 'Democrat'}, 412247: {'state': 'RI', 'name': 'Sen. Sheldon Whitehouse [D, 2007-2024]', 'party': 'Democrat'}, 412248: {'state': 'TN', 'name': 'Sen. Bob Corker [R, 2007-2018]', 'party': 'Republican'}, 412251: {'state': 'WY', 'name': 'Sen. John Barrasso [R, 2007-2018]', 'party': 'Republican'}, 412269: {'state': 'LA', 'name': 'Sen. Bill Cassidy [R]', 'party': 'Republican'}, 412281: {'state': 'NM', 'name': 'Sen. Martin Heinrich [D, 2013-2024]', 'party': 'Democrat'}, 412305: {'state': 'MI', 'name': 'Sen. Gary Peters [D]', 'party': 'Democrat'}, 412321: {'state': 'VA', 'name': 'Sen. Mark Warner [D]', 'party': 'Democrat'}, 412322: {'state': 'ID', 'name': 'Sen. James Risch [R]', 'party': 'Republican'}, 412323: {'state': 'NH', 'name': 'Sen. Jeanne Shaheen [D]', 'party': 'Democrat'}, 412325: {'state': 'OR', 'name': 'Sen. Jeff Merkley [D]', 'party': 'Democrat'}, 412330: {'state': 'CO', 'name': 'Sen. Michael Bennet [D]', 'party': 'Democrat'}, 412390: {'state': 'DE', 'name': 'Sen. Chris Coons [D]', 'party': 'Democrat'}, 412391: {'state': 'WV', 'name': 'Sen. Joe Manchin III [D, 2010-2024]', 'party': 'Democrat'}, 412406: {'state': 'CO', 'name': 'Sen. Cory Gardner [R]', 'party': 'Republican'}, 412428: {'state': 'IN', 'name': 'Sen. Todd Young [R]', 'party': 'Republican'}, 412464: {'state': 'OK', 'name': 'Sen. James Lankford [R]', 'party': 'Republican'}, 412471: {'state': 'SC', 'name': 'Sen. Tim Scott [R]', 'party': 'Republican'}, 412490: {'state': 'CT', 'name': 'Sen. Richard Blumenthal [D]', 'party': 'Democrat'}, 412491: {'state': 'FL', 'name': 'Sen. Marco Rubio [R]', 'party': 'Republican'}, 412492: {'state': 'KY', 'name': 'Sen. Rand Paul [R]', 'party': 'Republican'}, 412494: {'state': 'ND', 'name': 'Sen. John Hoeven [R]', 'party': 'Republican'}, 412495: {'state': 'UT', 'name': 'Sen. Mike Lee [R]', 'party': 'Republican'}, 412496: {'state': 'WI', 'name': 'Sen. Ron Johnson [R]', 'party': 'Republican'}, 412507: {'state': 'HI', 'name': 'Sen. Brian Schatz [D]', 'party': 'Democrat'}, 412508: {'state': 'AR', 'name': 'Sen. Tom Cotton [R]', 'party': 'Republican'}, 412533: {'state': 'IL', 'name': 'Sen. Tammy Duckworth [D]', 'party': 'Democrat'}, 412542: {'state': 'MA', 'name': 'Sen. Elizabeth Warren [D, 2013-2024]', 'party': 'Democrat'}, 412545: {'state': 'ME', 'name': 'Sen. Angus King [I, 2013-2024]', 'party': 'Independent'}, 412549: {'state': 'MT', 'name': 'Sen. Steve Daines [R]', 'party': 'Republican'}, 412554: {'state': 'ND', 'name': 'Sen. Heidi Heitkamp [D, 2013-2018]', 'party': 'Democrat'}, 412556: {'state': 'NE', 'name': 'Sen. Deb Fischer [R, 2013-2024]', 'party': 'Republican'}, 412573: {'state': 'TX', 'name': 'Sen. Ted Cruz [R, 2013-2024]', 'party': 'Republican'}, 412582: {'state': 'VA', 'name': 'Sen. Timothy “Tim” Kaine [D, 2013-2024]', 'party': 'Democrat'}, 412598: {'state': 'NJ', 'name': 'Sen. Cory Booker [D]', 'party': 'Democrat'}, 412665: {'state': 'AK', 'name': 'Sen. Dan Sullivan [R]', 'party': 'Republican'}, 412666: {'state': 'GA', 'name': 'Sen. David Perdue [R]', 'party': 'Republican'}, 412667: {'state': 'IA', 'name': 'Sen. Joni Ernst [R]', 'party': 'Republican'}, 412668: {'state': 'NC', 'name': 'Sen. Thom Tillis [R]', 'party': 'Republican'}, 412669: {'state': 'SD', 'name': 'Sen. Mike Rounds [R]', 'party': 'Republican'}, 412671: {'state': 'NE', 'name': 'Sen. Benjamin Sasse [R]', 'party': 'Republican'}, 412678: {'state': 'CA', 'name': 'Sen. Kamala Harris [D]', 'party': 'Democrat'}, 412679: {'state': 'LA', 'name': 'Sen. John Kennedy [R]', 'party': 'Republican'}, 412680: {'state': 'NH', 'name': 'Sen. Margaret “Maggie” Hassan [D]', 'party': 'Democrat'}, 412681: {'state': 'NV', 'name': 'Sen. Catherine Cortez Masto [D]', 'party': 'Democrat'}, 412741: {'state': 'AL', 'name': 'Sen. Doug Jones [D]', 'party': 'Democrat'}, 412742: {'state': 'MN', 'name': 'Sen. Tina Smith [D, 2018-2020]', 'party': 'Democrat'}, 412743: {'state': 'MS', 'name': 'Sen. Cindy Hyde-Smith [R, 2018-2020]', 'party': 'Republican'}})

In [289]:
G.nodes[300002]['name']

'Sen. Lamar Alexander [R]'

In [295]:
import bokeh
from bokeh.plotting import figure, output_notebook, show
from bokeh.models import Plot, Range1d, MultiLine, Circle, HoverTool, BoxZoomTool, ResetTool, PanTool, WheelZoomTool
#from bokeh.models.graphs import from_networkx, NodesAndLinkedEdges, EdgesAndLinkedNodes
#from bokeh.models.resources import INLINE
#output_notebook(resources=INLINE)